FROM public.ecr.aws/lambda/python:3.11

RUN yum update -y
RUN yum install -y wget tar xz

RUN mkdir -p /usr/local/bin/ffmpeg
WORKDIR /usr/local/bin/ffmpeg
# https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-6.0.1-i686-static.tar.xz
RUN wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
RUN tar xvf ffmpeg-release-amd64-static.tar.xz
RUN mv ffmpeg-7.0.1-amd64-static/ffmpeg .
RUN ln -s /usr/local/bin/ffmpeg/ffmpeg /usr/bin/ffmpeg
RUN ln -s /usr/local/bin/ffmpeg/ffprobe /usr/bin/ffprobe
